
import { Unit, InventoryItem, InboundLog, OutboundLog, Category, Supplier } from '../types';

// Initial categories
export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'قرطاسية' },
  { id: 'cat-2', name: 'أثاث' },
  { id: 'cat-3', name: 'تجهيزات تقنية' },
  { id: 'cat-4', name: 'مواد نظافة' }
];

// Initial suppliers
export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup-1', name: 'شركة الأمل للقرطاسية', contactPerson: 'أحمد محمد', phone: '029-12-34-56', email: 'contact@amal-stationery.dz' },
  { id: 'sup-2', name: 'مؤسسة النور للأثاث المكتبي', contactPerson: 'سعيد علي', phone: '029-98-76-54' },
  { id: 'sup-3', name: 'تكنولوجيا المستقبل للأجهزة', contactPerson: 'ليلى عمر', email: 'sales@future-tech.dz' }
];

// Initial inventory based on user provided list
export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'K/H/2024/001',
    barcode: '2132024001',
    name: 'ورق طباعة A4',
    description: 'كرتون ورق A4 عالي الجودة للطباعة الإدارية.',
    category: 'قرطاسية',
    unit: Unit.CARTON,
    initialStock: 58,
    inbound: 92,
    outbound: 0,
    currentQty: 150,
    reorderLevel: 10
  },
  {
    id: 'K/H/2024/002',
    barcode: '2132024002',
    name: 'حبر طابعة TK-4105',
    description: 'خرطوشة حبر طابعة ليزرية متوافقة.',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 32,
    inbound: 0,
    outbound: 0,
    currentQty: 32,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/003',
    barcode: '2132024003',
    name: 'إطار شهادة زجاجي A4',
    description: 'إطار حائط زجاجي فاخر للمقاس العالمي A4.',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 177,
    inbound: 0,
    outbound: 0,
    currentQty: 177,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/004',
    barcode: '2132024004',
    name: 'إطار شهادة زجاجي A3',
    description: 'إطار حائط زجاجي فاخر للمقاس A3.',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 60,
    inbound: 90,
    outbound: 0,
    currentQty: 150,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/005',
    barcode: '2132024005',
    name: 'إطار شهادة خشبي A3',
    description: 'إطار خشبي كلاسيكي للمقاس A3.',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 60,
    inbound: 90,
    outbound: 0,
    currentQty: 150,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/006',
    barcode: '2132024006',
    name: 'سجل البريد الوارد',
    description: 'سجل رسمي لتدوين المراسلات الواردة.',
    category: 'قرطاسية',
    unit: Unit.RECORD,
    initialStock: 30,
    inbound: 20,
    outbound: 0,
    currentQty: 50,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/007',
    barcode: '2132024007',
    name: 'سجل البريد الصادر',
    description: 'سجل رسمي لتدوين المراسلات الصادرة.',
    category: 'قرطاسية',
    unit: Unit.RECORD,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/008',
    barcode: '2132024008',
    name: 'سجل 2 MAIN',
    description: 'سجل إداري رئيسي للعمليات المخزنية.',
    category: 'قرطاسية',
    unit: Unit.RECORD,
    initialStock: 50,
    inbound: 20,
    outbound: 0,
    currentQty: 70,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/009',
    barcode: '2132024009',
    name: 'حقيبة جلدية',
    description: 'حقيبة وثائق جلدية عالية الجودة.',
    category: 'قرطاسية',
    unit: Unit.BAG,
    initialStock: 34,
    inbound: 0,
    outbound: 0,
    currentQty: 34,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/010',
    barcode: '2132024010',
    name: 'قلم جاف أزرق',
    description: 'علبة أقلام جاف زرقاء (50 قطعة).',
    category: 'قرطاسية',
    unit: Unit.BOX,
    initialStock: 22,
    inbound: 0,
    outbound: 0,
    currentQty: 22,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/011',
    barcode: '2132024011',
    name: 'حبر ختم',
    description: 'علبة حبر مخصصة للأختام الرسمية.',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 140,
    inbound: 0,
    outbound: 0,
    currentQty: 140,
    reorderLevel: 10
  },
  {
    id: 'K/H/2023/012',
    barcode: '2132026012',
    name: 'ساعة حائطية صغيرة',
    description: 'ساعة حائطية صغيرة بلاستيك',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 3,
    inbound: 0,
    outbound: 0,
    currentQty: 3,
    reorderLevel: 5
  },
  {
    id: 'K/H/2023/013',
    barcode: '2132026013',
    name: 'كرة سلة',
    description: 'النشاطات الرياضية',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/014',
    barcode: '2132026014',
    name: 'كاس الجوائز الرياضة',
    description: 'النشاطات الرياضية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 5
  },
  {
    id: 'K/H/2024/015',
    barcode: '2132026015',
    name: 'ميدالية تتويج',
    description: 'ميدالية تتويج متوسطة الحجم بالوان العلم الوطني',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 3,
    inbound: 12,
    outbound: 0,
    currentQty: 15,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/016',
    barcode: '2132026016',
    name: 'ورق طباعة A3',
    description: 'RAM',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 40,
    inbound: 0,
    outbound: 0,
    currentQty: 40,
    reorderLevel: 5
  },
  {
    id: 'K/H/2025/017',
    barcode: '2132026017',
    name: 'درع كريستال',
    description: 'درع للتكريمات',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 31,
    inbound: 0,
    outbound: 0,
    currentQty: 31,
    reorderLevel: 5
  },
  {
    id: 'K/H/2026/018',
    barcode: '2132026018',
    name: 'طقم كؤوس شاي',
    description: 'طقم من 06كؤوس بصحون',
    category: 'أثاث',
    unit: Unit.BOTTLE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2026/019',
    barcode: '2132026019',
    name: 'لوحة ذكية 5G',
    description: 'للتكريمات',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/020',
    barcode: '2132026020',
    name: 'ورق امتحان FEUILLE D EXAMEN',
    description: '1000FLMP',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 100
  },
  {
    id: 'K/H/2022/021',
    barcode: '2132026021',
    name: 'BROSSE TABLEAU ممسحة سبورة',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/022',
    barcode: '2132026022',
    name: 'cart rfid en pvc بطاقة الطالب',
    description: 'بطاقة الطالب للطبع',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 3000,
    inbound: 4823,
    outbound: 0,
    currentQty: 7823,
    reorderLevel: 500
  },
  {
    id: 'K/H/2022/023',
    barcode: '2132026023',
    name: 'علبة صيدلة (صغير)',
    description: 'حجم صغير',
    category: 'أثاث',
    unit: Unit.BOX,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/024',
    barcode: '2132026024',
    name: 'علبة صيدلة (كبير)',
    description: 'حجم كبير',
    category: 'أثاث',
    unit: Unit.BOX,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/025',
    barcode: '2132026025',
    name: 'مقبض نوافذ',
    description: 'مقبض نوافذ pvc',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 50,
    inbound: 0,
    outbound: 0,
    currentQty: 50,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/026',
    barcode: '2132026026',
    name: 'مفك بر اغي turnvice',
    description: 'مختلف الاحجام',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 15,
    inbound: 0,
    outbound: 0,
    currentQty: 15,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/027',
    barcode: '2132026027',
    name: 'مطرقة حجم متوسط',
    description: 'مطرقة يدوية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/028',
    barcode: '2132026028',
    name: 'طقم مفاتيح ربط molette',
    description: 'طقم متكون من 4 قطع',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/029',
    barcode: '2132026029',
    name: 'كلاب قطع كهربائي pince coupante',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/030',
    barcode: '2132026030',
    name: 'طقم مفاتيخ قطري jeu de cles allen',
    description: 'اشغال الصياتة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/031',
    barcode: '2132026031',
    name: 'طقم مفاتيخ سداسي jeu de clés males',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/032',
    barcode: '2132026032',
    name: 'جهاز قياس شدة التيار الكهربائي multimetre',
    description: 'اشغال الصياتة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/033',
    barcode: '2132026033',
    name: 'قاطع التيار الكهربائي c20',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/034',
    barcode: '2132026034',
    name: 'ماخذ كهربائي خارجي bms',
    description: 'اشغال الصياتة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/035',
    barcode: '2132026035',
    name: 'مثبت خر ساني goujon 12',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/036',
    barcode: '2132026035',
    name: 'مصباح لاد tube 120cm',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 60,
    inbound: 0,
    outbound: 0,
    currentQty: 60,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/037',
    barcode: '2132026037',
    name: 'مصباح لاد tube 60cm',
    description: 'اشغال الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 40,
    inbound: 0,
    outbound: 0,
    currentQty: 40,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/038',
    barcode: '2132026038',
    name: 'عصا مكنسة',
    description: 'النضافة',
    category: 'مواد نظافة',
    unit: Unit.PIECE,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/039',
    barcode: '2132026039',
    name: 'معطر الجو',
    description: 'نضافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/040',
    barcode: '2132026040',
    name: 'مكنسة',
    description: 'النضافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/041',
    barcode: '2132026041',
    name: 'ماسحة ارضية frottoir',
    description: 'النضافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/042',
    barcode: '2132026042',
    name: 'صابون مسحوق 360غ',
    description: 'النضافة',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/043',
    barcode: '2132026043',
    name: 'ورق حمام',
    description: 'حجم صغير',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/044',
    barcode: '2132026044',
    name: 'صابون سائل 5ل',
    description: 'مواد نظافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 21,
    inbound: 0,
    outbound: 0,
    currentQty: 21,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/045',
    barcode: '2132026045',
    name: 'جافيل 1 ل',
    description: 'النضافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 35,
    inbound: 0,
    outbound: 0,
    currentQty: 35,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/046',
    barcode: '2132026046',
    name: 'قريزيل 1 ل',
    description: 'النضافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 60,
    inbound: 0,
    outbound: 0,
    currentQty: 60,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/047',
    barcode: '2132026047',
    name: 'مثقاب ومفك براغي لا سلكي vicieuse',
    description: 'crown .الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/048',
    barcode: '2132026048',
    name: 'سجل 3 main',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 35,
    inbound: 0,
    outbound: 0,
    currentQty: 35,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/049',
    barcode: '2132026049',
    name: 'مبرد مياه fontainfraiche',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/050',
    barcode: '2132026050',
    name: 'سلم معدني قابل للطي 1,5m escabeau',
    description: 'الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/051',
    barcode: '2132026051',
    name: 'سلم المنيوم 4 م',
    description: 'الصيانة',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/052',
    barcode: '2132026052',
    name: 'مبراة taille crayon',
    description: 'المكتبية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/053',
    barcode: '2132026053',
    name: 'علبة ارشيف boit archive gm15 cm',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 30,
    inbound: 0,
    outbound: 0,
    currentQty: 30,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/054',
    barcode: '2132026054',
    name: 'علبة ارشيف boit archive gm20 cm',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/055',
    barcode: '2132026055',
    name: 'علبة ارشيف boit archive10cm',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 50,
    inbound: 40,
    outbound: 0,
    currentQty: 90,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/056',
    barcode: '2132026056',
    name: 'crayon قلم رصاص',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/057',
    barcode: '2132026057',
    name: 'ختم تاريخ dateur',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/058',
    barcode: '2132026058',
    name: 'قرفاز graveuse papier',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 60,
    inbound: 0,
    outbound: 0,
    currentQty: 60,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/059',
    barcode: '2132026059',
    name: 'مسطرة règle 30cm',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 101,
    inbound: 0,
    outbound: 0,
    currentQty: 101,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/060',
    barcode: '2132026060',
    name: 'قلم تصحيح stylo correcteur',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 50,
    inbound: 0,
    outbound: 0,
    currentQty: 50,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/061',
    barcode: '2132026061',
    name: 'مقص ciseau',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 50,
    inbound: 0,
    outbound: 0,
    currentQty: 50,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/062',
    barcode: '2132026062',
    name: 'ممحاة gomme',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 150,
    inbound: 0,
    outbound: 0,
    currentQty: 150,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/063',
    barcode: '2132026063',
    name: 'سجل 3 MAIN',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 35,
    inbound: 0,
    outbound: 0,
    currentQty: 35,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/064',
    barcode: '2132026064',
    name: 'ورق مقوئ papier cartonne',
    description: 'ram',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 30,
    inbound: 0,
    outbound: 0,
    currentQty: 30,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/065',
    barcode: '2132026065',
    name: 'ظرف بريدي enveloppe 126',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 1000,
    inbound: 12500,
    outbound: 10000,
    currentQty: 3500,
    reorderLevel: 500
  },
  {
    id: 'K/H/2022/066',
    barcode: '2132026066',
    name: 'ظرف بريدي enveloppef24',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/067',
    barcode: '2132026067',
    name: 'ظرف بريدي enveloppe f16',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 2000,
    inbound: 0,
    outbound: 0,
    currentQty: 2000,
    reorderLevel: 200
  },
  {
    id: 'K/H/2022/068',
    barcode: '2132026068',
    name: 'قلم جاف ازر ق stylo bleu',
    description: 'علبة 50قلم',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 30,
    inbound: 0,
    outbound: 0,
    currentQty: 30,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/069',
    barcode: '2132026069',
    name: 'قلم جاف احمر stylo rouge',
    description: 'علبة 50قلم',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 3,
    inbound: 0,
    outbound: 0,
    currentQty: 3,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/070',
    barcode: '2132026070',
    name: 'قلم جاف اسود stylo noir',
    description: 'علبىة 50قلم',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/071',
    barcode: '2132026071',
    name: 'حامل اقلام معدني pot a crayons en métal',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 30,
    inbound: 0,
    outbound: 0,
    currentQty: 30,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/072',
    barcode: '2132026072',
    name: 'ورق اليلاستيكي شفاف pochette transparente A4',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 500,
    inbound: 0,
    outbound: 0,
    currentQty: 500,
    reorderLevel: 50
  },
  {
    id: 'K/H/2022073',
    barcode: '2132026073',
    name: 'ملف التعليق dossier suspendu',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 100,
    inbound: 0,
    outbound: 0,
    currentQty: 100,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/074',
    barcode: '2132026074',
    name: 'حامل lختام porte tampons',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/075',
    barcode: '2132026075',
    name: 'منظم مكتب port bloc notes',
    description: 'منظم مكتب حامل اقلام وورق صغير',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/076',
    barcode: '2132026076',
    name: 'حامل شهادة ورقي خشن دو واجهة لوحية porte diplôme',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 150,
    inbound: 0,
    outbound: 37,
    currentQty: 113,
    reorderLevel: 20
  },
  {
    id: 'K/H/2022/077',
    barcode: '2132026077',
    name: 'قلم سبورة ازرق marqueur blue',
    description: 'علبة 12 قلم',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 65,
    inbound: 0,
    outbound: 0,
    currentQty: 65,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/078',
    barcode: '2132026078',
    name: 'قلم سبورة احمر marqueur rouge',
    description: 'علبة 12قلم',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 10,
    inbound: 0,
    outbound: 0,
    currentQty: 10,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/079',
    barcode: '2132026079',
    name: 'قلم سبورة اسود marqueur noire',
    description: 'علبة 12قلم',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 35,
    inbound: 0,
    outbound: 0,
    currentQty: 35,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/080',
    barcode: '2132026080',
    name: 'chargeur marquer noire',
    description: 'علبة 24 وحدة',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 25,
    inbound: 0,
    outbound: 0,
    currentQty: 25,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/081',
    barcode: '2132026081',
    name: 'chargeur marquer bleu',
    description: 'علبة 24 وحدة',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 40,
    inbound: 0,
    outbound: 0,
    currentQty: 40,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022082',
    barcode: '2132026082',
    name: 'chargeur marquer rouge',
    description: '24 pcs',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/083',
    barcode: '2132026083',
    name: 'منشار حديدي يدوي',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/084',
    barcode: '2132026084',
    name: 'حامل ملفات ورقيchemise dossier',
    description: 'ram',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 0,
    inbound: 24,
    outbound: 0,
    currentQty: 24,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/085',
    barcode: '2132026085',
    name: 'حامل ملفات ورقيsous chemise dossier',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 48,
    inbound: 0,
    outbound: 0,
    currentQty: 48,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/086',
    barcode: '2132026086',
    name: 'حاوية نظافة بلاستيك حجم صغير',
    description: 'مواد نظافة',
    category: 'مواد نظافة',
    unit: Unit.UNIT,
    initialStock: 25,
    inbound: 0,
    outbound: 0,
    currentQty: 25,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/087',
    barcode: '2132026087',
    name: 'حاوية نظافة بلاستيك حجم متوسط',
    description: 'مواد نظافة',
    category: 'مواد نظافة',
    unit: Unit.PIECE,
    initialStock: 9,
    inbound: 0,
    outbound: 0,
    currentQty: 9,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/088',
    barcode: '2132026088',
    name: 'حاوية نظافة بلاستيك حجم كبير',
    description: 'مواد نظافة',
    category: 'مواد نظافة',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/089',
    barcode: '2132026089',
    name: 'منظف السبورة',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 20,
    inbound: 0,
    outbound: 0,
    currentQty: 20,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/090',
    barcode: '2132026090',
    name: 'BROSSE TABLEAU ممسحة سبورة',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 150,
    inbound: 1,
    outbound: 0,
    currentQty: 151,
    reorderLevel: 20
  },
  {
    id: 'ك/ح/ع/س /2025/245',
    barcode: '2132025245',
    name: 'طابعة canon MF 3010',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/092',
    barcode: '2132026092',
    name: 'ورق مسودة feuille brouillon multi',
    description: 'علبة 05 ram',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 90,
    inbound: 0,
    outbound: 0,
    currentQty: 90,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/093',
    barcode: '2132026093',
    name: 'نظارات عمال',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/094',
    barcode: '2132026094',
    name: 'بدلة رياضية survetement',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/095',
    barcode: '2132026095',
    name: 'قميص ملون للتدريب maillot d entraînement clore',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 13,
    inbound: 17,
    outbound: 0,
    currentQty: 30,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/096',
    barcode: '2132026096',
    name: 'بدلة اللعب tonue de match',
    description: 'short et maillot',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/097',
    barcode: '2132026097',
    name: 'حبر طابعة toner tk 435',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/098',
    barcode: '2132026098',
    name: 'حبر طابعة toner HP laser jet',
    description: '35A 36A 85A 78A',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 16,
    inbound: 0,
    outbound: 0,
    currentQty: 16,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/099',
    barcode: '2132026099',
    name: 'شريط الطباعة RIBBON CARTRIDGES',
    description: 'طباعة بطاعة الطالب',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 9,
    inbound: 0,
    outbound: 0,
    currentQty: 9,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/100',
    barcode: '2132026100',
    name: 'خرطوشة حبر CE312/CF352A',
    description: 'طابعةHP ملونة CP 1025 CP 10250NW M 175 A M175 NW',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2026/101',
    barcode: '2132026101',
    name: 'حاسوب مكتبي HP PRO TOWER 290 G9',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 5,
    inbound: 5,
    outbound: 0,
    currentQty: 10,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/102',
    barcode: '2132026102',
    name: 'مكبر صوت صغير للحاسوب SPEAKER',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/103',
    barcode: '2132026103',
    name: 'خرطوشة حبر TONER HP',
    description: 'HP 1102 P1102W M113 2 M1212NF',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 5,
    inbound: 0,
    outbound: 0,
    currentQty: 5,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/104',
    barcode: '2132026104',
    name: 'خرطوشة حبر TONER HP LASER JET',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 6,
    inbound: 0,
    outbound: 0,
    currentQty: 6,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/105',
    barcode: '2132026105',
    name: 'خرطوشة حبر TK 1130',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/106',
    barcode: '2132026106',
    name: 'خرطوشة حبر COLOR LASER JET',
    description: 'CF 352A CE 312A',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/107',
    barcode: '2132026107',
    name: 'خرطوشة حبر SAMSUNG TONER',
    description: 'SAMSUNGML 1610,2010,2010R 2010P,2510,2570,2570N,2571',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/108',
    barcode: '2132026108',
    name: 'مكثفة كهربائية CAPACITOR 35 UF/450V',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 9,
    inbound: 0,
    outbound: 0,
    currentQty: 9,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/109',
    barcode: '2132026109',
    name: 'مكثفة كهربائية CAPACITOR 50 UF/450V',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/110',
    barcode: '2132026110',
    name: 'مكثفة كهربائية CAPACITOR 50 UF/450V',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/111',
    barcode: '2132026111',
    name: 'شريط طباعة نقطية RUBAN ENCREUR',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 13,
    inbound: 0,
    outbound: 0,
    currentQty: 13,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/112',
    barcode: '2132026112',
    name: 'حبر طابعة TK-1110/1120',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 3,
    inbound: 0,
    outbound: 0,
    currentQty: 3,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022113',
    barcode: '2132026113',
    name: 'CABLE USB',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 5,
    inbound: 0,
    outbound: 1,
    currentQty: 4,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/114',
    barcode: '2132026114',
    name: 'CABLE USB IMPRIMANT',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/115',
    barcode: '2132026115',
    name: 'مكيف هواء CLIMATISAIR CONDOR 24000',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/116',
    barcode: '2132026116',
    name: 'مكيف هواء CLIMATISAIR CONDOR 18000',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/117',
    barcode: '2132026117',
    name: 'حاسوب مكتبي MICRO DESKTOP HP 290 G9',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/118',
    barcode: '2132026118',
    name: 'شاشة حاسوب LONOVO ECRAN 27',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/119',
    barcode: '2132026119',
    name: 'شاشة حاسوب ECRAN HP 24',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/120',
    barcode: '2132026120',
    name: 'شاشة حاسوب CONDOR ECRAN 27',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022121',
    barcode: '2132026121',
    name: 'شاشة حاسوب ENIGMA ECRAN 27',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/122',
    barcode: '2132026122',
    name: 'مساك اوراق',
    description: 'علبة 500 وحدة',
    category: 'قرطاسية',
    unit: Unit.BOTTLE,
    initialStock: 27,
    inbound: 0,
    outbound: 0,
    currentQty: 27,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/123',
    barcode: '2132026123',
    name: 'هاتف appareille telephone',
    description: 'Alcatel t22',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 0,
    inbound: 0,
    outbound: 0,
    currentQty: 0,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/124',
    barcode: '2132026124',
    name: 'طقم كؤوس قهوة',
    description: 'طقم 06 كؤوس بصحون',
    category: 'أثاث',
    unit: Unit.BOTTLE,
    initialStock: 22,
    inbound: 0,
    outbound: 0,
    currentQty: 22,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/125',
    barcode: '2132026125',
    name: 'راية علم وطني',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 60,
    inbound: 0,
    outbound: 0,
    currentQty: 60,
    reorderLevel: 10
  },
  {
    id: 'K/H/2022/126',
    barcode: '2132026126',
    name: 'طقم علم تشريفات مع حامل drapeau de prestige sur socle',
    description: 'la hampe le socle la lance le pavillon',
    category: 'أثاث',
    unit: Unit.PIECE,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/127',
    barcode: '2132026127',
    name: 'علم مكتب مع حامل mini drapeau avec support',
    description: 'أثاث',
    category: 'أثاث',
    unit: Unit.UNIT,
    initialStock: 11,
    inbound: 0,
    outbound: 0,
    currentQty: 11,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/128',
    barcode: '2132026128',
    name: 'حامل توقيع فاخر le port signature de lux e',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.RECORD,
    initialStock: 10,
    inbound: 0,
    outbound: 0,
    currentQty: 10,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/129',
    barcode: '2132026129',
    name: 'سلة نظافة بلاستيك',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.UNIT,
    initialStock: 66,
    inbound: 0,
    outbound: 0,
    currentQty: 66,
    reorderLevel: 10
  },
  {
    id: 'ك/ح /ع/س / 2025/245',
    barcode: '2132026130',
    name: 'طابعة canon 3010',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 1,
    outbound: 1,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/131',
    barcode: '2132026131',
    name: 'كابل شبكة câble réseau',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/132',
    barcode: '2132026132',
    name: 'كابل التغذية الكهربائية câble d alimentation',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 25,
    inbound: 0,
    outbound: 0,
    currentQty: 25,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/133',
    barcode: '2132026133',
    name: 'جهاز العرض الضوئي vidéoprojecteur professionnel',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/134',
    barcode: '2132026134',
    name: 'طابعة hp impimante multi fonction coleur lazer m182n',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 3,
    inbound: 0,
    outbound: 0,
    currentQty: 3,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/135',
    barcode: '2132026135',
    name: 'طابعة impimante multi fonction hp m236 d',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/136',
    barcode: '2132026136',
    name: 'الة نسخ photocopie a4 multi fonction kyocera 2135 35 ppm',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/137',
    barcode: '2132026137',
    name: 'مجمع ماخذ multiprise avec interrupteur m5',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/138',
    barcode: '2132026138',
    name: 'مجمع ماخذ multiprise avec interrupteur m3',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 5
  },
  {
    id: 'K/H/2022/139',
    barcode: '2132026139',
    name: 'لوحة مفاتيح',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 8,
    inbound: 0,
    outbound: 0,
    currentQty: 8,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/140',
    barcode: '2132026140',
    name: 'طابعة ناسخة canon dx 2430',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/141',
    barcode: '2132026141',
    name: 'جهاز تلحيم mma-300 crown',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/142',
    barcode: '2132026142',
    name: 'ورق متصل papier listing',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.CARTON,
    initialStock: 3,
    inbound: 0,
    outbound: 0,
    currentQty: 3,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/143',
    barcode: '2132026143',
    name: 'ورق مقوى ملون A4',
    description: '5 RAM',
    category: 'قرطاسية',
    unit: Unit.CARTON,
    initialStock: 12,
    inbound: 0,
    outbound: 0,
    currentQty: 12,
    reorderLevel: 2
  },
  {
    id: 'K/H/2022/144',
    barcode: '2132026144',
    name: 'تلفزيون كريستور 65P I6',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/145',
    barcode: '2132026145',
    name: 'قارىء بطاقات GENERIE',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/146',
    barcode: '2132026146',
    name: 'ماسح ضوئي SCANER A4 AVEC CHARGEUR DOCUMENT AUTOMATIQUE',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 2,
    inbound: 0,
    outbound: 0,
    currentQty: 2,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/147',
    barcode: '2132026147',
    name: 'حاسوب مكتبي بدون شاشة LONOVO',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.UNIT,
    initialStock: 4,
    inbound: 0,
    outbound: 0,
    currentQty: 4,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/148',
    barcode: '2132026148',
    name: 'طابعة CANON LBP631Cw',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 1,
    inbound: 0,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/149',
    barcode: '2132026149',
    name: 'طابعة متعددة الوظائف imprimante multi fonctin A4 marque reconnue',
    description: 'تجهيزات تقنية',
    category: 'تجهيزات تقنية',
    unit: Unit.PIECE,
    initialStock: 0,
    inbound: 1,
    outbound: 0,
    currentQty: 1,
    reorderLevel: 1
  },
  {
    id: 'K/H/2022/150',
    barcode: '2132026150',
    name: 'سجل ملاحظات صغير bloc note',
    description: 'قرطاسية',
    category: 'قرطاسية',
    unit: Unit.RECORD,
    initialStock: 15,
    inbound: 0,
    outbound: 0,
    currentQty: 15,
    reorderLevel: 5
  }
];

export const INITIAL_INBOUND: InboundLog[] = [];
export const INITIAL_OUTBOUND: OutboundLog[] = [];
